exclude: |
  (?x)(
    ^_generated/
    | ^idl/
  )
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: generate
        name: Generate codes from schemas
        language: system
        types: [directory]
        pass_filenames: false
        entry: make generate

  - repo: local
    hooks:
      - id: golangci-lint
        name: Lint with golangci-lint
        language: system
        types: [go]
        pass_filenames: false
        entry: sh
        args:
          - -c
          - |
            PATH="${PATH}:${PWD}/.bin" golangci-lint run --fix

      - id: go-test
        name: Run tests
        language: system
        types: [go]
        pass_filenames: false
        entry: go test
